version: "3"
services:    
      server:
        build: "./server"
        image: "leo727268082/meltest-server"
        ports: 
          - "80:5000"
        volumes:
          - "./server:/app"

      client:
        build: "./client"
        image: "leo727268082/meltest-client"
        ports:
          - "3000:3000"
        volumes:
          - "./client:/user/src/app"
        depends_on: 
          - "server"