---
- name: Enable CouchDB cluster
  ansible.builtin.uri:
    url: http://{{ coordinator }}:5984/_cluster_setup
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: application/json
    body_format: json
    body:
      action: enable_cluster
      bind_address: 0.0.0.0
      username: "{{ couchdb_user }}"
      password: "{{ couchdb_password }}"
      port: 5984
      remote_node: "{{ inventory_hostname }}" 
      node_count: 3
      remote_current_user: "{{ couchdb_user }}"
      remote_current_password: "{{ couchdb_password }}"

- name: Add nodes to CouchDB cluster
  ansible.builtin.uri:
    url: http://{{ coordinator }}:5984/_cluster_setup
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: application/json
    body_format: json
    body:
      action: add_node
      host: "{{ inventory_hostname }}"
      port: 5984
      username: "{{ couchdb_user }}"
      password: "{{ couchdb_password }}"

- name: Test connection
  ansible.builtin.uri:
    url: http://{{ coordinator }}:5984/
    method: GET
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
  run_once: true

- name: Finish CouchDB cluster setup
  ansible.builtin.uri:
    url: http://{{ coordinator }}:5984/_cluster_setup
    method: POST
    user: "{{ couchdb_user }}"
    password: "{{ couchdb_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: application/json
    status_code: 200, 201
    body_format: json
    body:
      action: finish_cluster   
  run_once: true