---
- name: Create a security group
  openstack.cloud.security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'


- name: Create a list of security group names
  set_fact:
    sg_names: '{{ sg_names|default([]) + [ item.name ] }}'
  loop: '{{ security_groups }}'

# - name: "Display all security groups created"
#   debug:
#     msg: "Security group(s) {{ sg_names }} have been created."


- name: Create security group rules for public
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: present
  loop: '{{ security_group_rules_public }}'


# Create security group rules private 
- name: Create security group rules for CouchDB
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_group: '{{ item.remote_group }}'
    state: present
  loop: '{{ security_group_rules_private }}'
